---
version: 2
triggers: [ ]

plan:
  project-key: CL
  key: TTED
  name: TrustTunnel - Deploy Docker Image

stages:
  - Build and Push Docker Image:
      manual: false
      final: false
      jobs:
        - Build and Push Docker Image

Build and Push Docker Image:
  key: BDI
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            printf "%b\n" "${bamboo_sshSecretKey}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            git fetch --unshallow || true
            git fetch --force --tags
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
            TAG=v${VERSION}

            DOCKER_IMAGE_REPO="trusttunnel/trusttunnel-endpoint"
            DOCKER_IMAGE_VERSION_TAG="${DOCKER_IMAGE_REPO}:${TAG}"
            DOCKER_IMAGE_LATEST_TAG="${DOCKER_IMAGE_REPO}:latest"

            set +x
            echo "${bamboo.trusttunnelDockerHubPassword}" | docker login -u "${bamboo.trusttunnelDockerHubUsername}" --password-stdin
            set -x

            cat << EOF > buildkitd.toml
            [worker.oci]
              max-parallelism = 1
            EOF

            docker buildx create --name trusttunnel-builder --use --config buildkitd.toml || docker buildx use trusttunnel-builder
            docker buildx build \
                --platform linux/amd64,linux/arm64 \
              -f Dockerfile.prebuilt \
              --build-arg "TT_VERSION=${VERSION}" \
                -t "${DOCKER_IMAGE_VERSION_TAG}" \
                -t "${DOCKER_IMAGE_LATEST_TAG}" \
                --push .
  requirements:
    - ephemeral-linux
    - image: registry.int.agrd.dev/linux/debian13-bamboo:latest
  artifact-subscriptions: [ ]
  artifacts: [ ]

repositories:
  - core-libs/vpn-libs-endpoint:
      scope: global

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: [ ]

labels: [ ]

other:
  concurrent-build-plugin: system-default
