[[projects]]
name = "Xray-core"
path = "./Xray"
url = "https://github.com/XTLS/Xray-core.git"
branch = "main"
start_commit = "5d94a62a83073bc4aa378fb7e2198e15878e90da"
recurse_submodules = false

[[projects]]
name = "sing-box"
path = "./sing-box"
url = "https://github.com/SagerNet/sing-box.git"
branch = "stable"
start_commit = "93b7328"
recurse_submodules = false

[[projects]]
name = "hiddify-app"
path = "./hiddify/hiddify-app"
url = "https://github.com/hiddify/hiddify-app.git"
branch = "main"
start_commit = "379a672254450733455458e8c3a4d40c63a9c98d"
recurse_submodules = false

[[projects]]
name = "TrustTunnel"
path = "./TrustTunnel/TrustTunnel"
url = "https://github.com/TrustTunnel/TrustTunnel"
branch = "master"
start_commit = "6b18c5d7f180cc2a34cc6e3894cc72d52cc02077"
recurse_submodules = false

[[projects]]
name = "TrustTunnelClient"
path = "./TrustTunnel/TrustTunnelClient"
url = "https://github.com/TrustTunnel/TrustTunnelClient"
branch = "master"
start_commit = "33e14f7"
recurse_submodules = false

[[projects]]
name = "TrustTunnelFlutterClient"
path = "./TrustTunnel/TrustTunnelFlutterClient"
url = "https://github.com/TrustTunnel/TrustTunnelFlutterClient.git"
branch = "master"
start_commit = "896e9e1"
recurse_submodules = false

[[projects]]
name = "telemt"
path = "./telegram/telemt"
url = "https://github.com/telemt/telemt.git"
branch = "main"
start_commit = "c47495d"
recurse_submodules = false

[[projects]]
name = "MTProxy"
path = "./telegram/MTProxy"
url = "https://github.com/TelegramMessenger/MTProxy.git"
branch = "master"
start_commit = "580909c"
recurse_submodules = false

[[projects]]
name = "dpibreak"
path = "./antiDPI/dpibreak"
url = "https://github.com/dilluti0n/dpibreak.git"
branch = "master"
start_commit = "f65c78f9b028533d620a67c846e92f6f443dd5bd"
recurse_submodules = false

[[projects]]
name = "zapret"
path = "./antiDPI/zapret"
url = "https://github.com/bol-van/zapret.git"
branch = "master"
start_commit = "76764ad6b0ee7d3991c97e7b8c24d53189d25c28"
recurse_submodules = false

